import type { Opportunity } from "./types";

const checked = "2026-09-12T05:40:00.000Z";

export const demoOpportunities: Opportunity[] = [
  {
    id: "os-ember-auth-214",
    category: "open-source",
    owner: "Northstar Labs",
    repo: "ember-auth",
    avatar: "NL",
    issueNumber: 214,
    title: "Improve expired-session error messages",
    summary: "Replace a generic authentication failure with actionable messages for expired and revoked sessions, including coverage for both paths.",
    language: "TypeScript",
    languageColor: "#3178c6",
    labels: ["good first issue", "ux", "tests"],
    experience: "Beginner",
    status: "unassigned",
    statusDetail: "No assignee or visible claim comment was found in this demo snapshot.",
    checkedAt: checked,
    updatedAt: "2026-09-12T02:10:00.000Z",
    maintainerActivity: "Maintainer replied to 4 of 5 newcomer issues",
    activityWindow: "Observed across 5 issues in the last 30 days",
    caution: "Unassigned is not a guarantee—leave a short scope check before coding.",
    assignment: "This demo repository does not require assignment before a contributor starts.",
    visibleClaims: "No visible claim comments in the issue thread.",
    linkedPrs: "No linked pull requests detected.",
    blockers: "None documented.",
    startSteps: ["Read the error-handling section in CONTRIBUTING.md.", "Comment with the two states you plan to cover.", "Add failing tests before changing the message mapping."],
    setup: ["Node.js 22 and pnpm 9", "Run pnpm test auth --runInBand", "Keep changes inside packages/session unless maintainers confirm broader scope"],
    avoid: [
      { kind: "Official repository rule", text: "User-facing strings must use the existing message catalogue.", source: { label: "Demo CONTRIBUTING.md", href: "#demo-source-note", kind: "guide" } },
      { kind: "General suggestion", text: "Confirm the wording in the issue before touching translation files." }
    ],
    sources: [{ label: "Demo contribution guide", href: "#demo-source-note", kind: "guide" }]
  },
  {
    id: "os-pixel-cache-88",
    category: "open-source",
    owner: "Patchbay",
    repo: "pixel-cache",
    avatar: "PB",
    issueNumber: 88,
    title: "Add WebP fixtures to cache-key tests",
    summary: "Extend the image fixture matrix so query parameters and content negotiation produce stable cache keys for WebP responses.",
    language: "Rust",
    languageColor: "#dea584",
    labels: ["help wanted", "testing"],
    experience: "Intermediate",
    status: "ask-first",
    statusDetail: "The contribution guide asks first-time contributors to confirm test-fixture changes.",
    checkedAt: "2026-09-12T04:58:00.000Z",
    updatedAt: "2026-09-11T16:20:00.000Z",
    maintainerActivity: "2 maintainer replies observed",
    activityWindow: "Current issue thread only",
    caution: "The fixture format is being discussed; confirm the expected binary size first.",
    assignment: "Assignment is optional, but approval is requested for new binary fixtures.",
    visibleClaims: "One contributor asked a question but did not claim the work.",
    linkedPrs: "No linked pull request found.",
    blockers: "Expected maximum fixture size is not yet documented.",
    startSteps: ["Ask whether generated 2 KB fixtures are acceptable.", "Wait for a maintainer response before committing binaries.", "Run the cache-key test group locally."],
    setup: ["Stable Rust toolchain", "Run cargo test cache_key", "Generate fixtures with scripts/make-fixtures.sh"],
    avoid: [{ kind: "Official repository rule", text: "Do not add binary fixtures without maintainer confirmation.", source: { label: "Demo contributor note", href: "#demo-source-note", kind: "guide" } }],
    sources: [{ label: "Demo contributor note", href: "#demo-source-note", kind: "guide" }]
  },
  {
    id: "os-tiny-queue-301",
    category: "open-source",
    owner: "Tinystack",
    repo: "tiny-queue",
    avatar: "TS",
    issueNumber: 301,
    title: "Document retry jitter configuration",
    summary: "Add a concise configuration example and clarify how full jitter behaves when the maximum delay is omitted.",
    language: "Go",
    languageColor: "#00add8",
    labels: ["documentation", "good first issue"],
    experience: "Beginner",
    status: "possibly-claimed",
    statusDetail: "A contributor said they planned to work on this 18 hours ago; no PR is linked yet.",
    checkedAt: "2026-09-12T04:41:00.000Z",
    updatedAt: "2026-09-11T11:30:00.000Z",
    caution: "Check with the commenter before duplicating work.",
    assignment: "The repository does not use issue assignment consistently.",
    visibleClaims: "One recent intent-to-work comment is visible.",
    linkedPrs: "No linked PR found.",
    blockers: "None documented.",
    startSteps: ["Ask the recent commenter whether they are still working on it.", "If available, propose the exact docs section you will update."],
    setup: ["Documentation-only change", "Run markdownlint .", "Verify examples against examples/retry/main.go"],
    avoid: [{ kind: "General suggestion", text: "Do not open a competing PR while the recent claim is unresolved." }],
    sources: [{ label: "Demo issue thread", href: "#demo-source-note", kind: "issue" }]
  },
  {
    id: "os-orbit-cli-472",
    category: "open-source",
    owner: "Orbit Tools",
    repo: "orbit-cli",
    avatar: "OT",
    issueNumber: 472,
    title: "Support JSON output for plugin list",
    summary: "Introduce a machine-readable output option for the plugin listing command while preserving the existing terminal table.",
    language: "Python",
    languageColor: "#3572a5",
    labels: ["cli", "enhancement"],
    experience: "Intermediate",
    status: "linked-pr",
    statusDetail: "A pull request is linked and currently awaiting review.",
    checkedAt: "2026-09-12T03:20:00.000Z",
    updatedAt: "2026-09-10T20:00:00.000Z",
    caution: "Join the existing review instead of starting a parallel implementation.",
    assignment: "No assignee is shown.",
    visibleClaims: "The PR author posted an implementation note.",
    linkedPrs: "One open linked pull request.",
    blockers: "None documented.",
    startSteps: ["Review the linked work if you have relevant CLI experience.", "Otherwise, choose another available issue."],
    setup: ["Python 3.12", "Run uv run pytest tests/cli", "Snapshot changes need explicit review"],
    avoid: [{ kind: "General suggestion", text: "Avoid duplicating the linked implementation." }],
    sources: [{ label: "Demo linked PR", href: "#demo-source-note", kind: "pull-request" }]
  },
  {
    id: "os-leaflet-kit-51",
    category: "open-source",
    owner: "Maploom",
    repo: "leaflet-kit",
    avatar: "ML",
    issueNumber: 51,
    title: "Keyboard focus for layer toggles",
    summary: "Make custom layer toggles reachable by keyboard and expose their expanded state to assistive technology.",
    language: "JavaScript",
    languageColor: "#f1e05a",
    labels: ["accessibility", "frontend"],
    experience: "Intermediate",
    status: "blocked",
    statusDetail: "Blocked pending a decision on the public toggle API.",
    checkedAt: "2026-09-11T17:15:00.000Z",
    updatedAt: "2026-09-09T07:45:00.000Z",
    caution: "Do not implement until the linked API discussion is resolved.",
    assignment: "Assignment is not relevant while blocked.",
    visibleClaims: "No active claim.",
    linkedPrs: "A draft exploration was closed; the closure reason was not documented.",
    blockers: "Public API naming decision in progress.",
    startSteps: ["Follow the API discussion.", "Contribute keyboard-testing notes without implementing the unresolved API."],
    setup: ["Node.js 20", "Run npm run test:a11y", "Test with keyboard and at least one screen reader"],
    avoid: [{ kind: "Observed review pattern", text: "A prior draft was closed, but the available demo record does not establish why.", source: { label: "Demo review thread", href: "#demo-source-note", kind: "pull-request" } }],
    sources: [{ label: "Demo API discussion", href: "#demo-source-note", kind: "discussion" }]
  },
  {
    id: "os-streamline-19",
    category: "open-source",
    owner: "Signalworks",
    repo: "streamline",
    avatar: "SW",
    issueNumber: 19,
    title: "Expose batch-size metric",
    summary: "Add a batch-size histogram to the optional metrics adapter and document its cardinality implications.",
    language: "Java",
    languageColor: "#b07219",
    labels: ["observability", "metrics"],
    experience: "Advanced",
    status: "unknown",
    statusDetail: "The last successful check is older than 24 hours. Current availability is unknown.",
    checkedAt: "2026-09-10T01:10:00.000Z",
    updatedAt: "2026-09-08T09:00:00.000Z",
    caution: "Recheck the source before taking action; this record is stale.",
    assignment: "Unknown due to stale source data.",
    visibleClaims: "Unknown due to stale source data.",
    linkedPrs: "Unknown due to stale source data.",
    blockers: "Unknown.",
    startSteps: ["Open the source issue and verify its current state.", "Check for linked PRs and recent claim comments."],
    setup: ["Java 21", "Run ./gradlew metrics:test", "Include a cardinality note in the docs"],
    avoid: [{ kind: "General suggestion", text: "Treat all availability fields as unverified until a fresh check succeeds." }],
    sources: [{ label: "Demo source unavailable", href: "#demo-source-note", kind: "issue" }]
  },
  {
    id: "os-closed-144",
    category: "open-source",
    owner: "Paperclip",
    repo: "form-kit",
    avatar: "PC",
    issueNumber: 144,
    title: "Normalize optional date fields",
    summary: "This issue was completed and remains visible here to demonstrate how closed opportunities are handled.",
    language: "TypeScript",
    languageColor: "#3178c6",
    labels: ["schema", "completed"],
    experience: "Beginner",
    status: "closed",
    statusDetail: "The issue is closed and is not available to start.",
    checkedAt: "2026-09-12T03:55:00.000Z",
    updatedAt: "2026-09-12T03:50:00.000Z",
    caution: "Closed—browse related open issues instead.",
    assignment: "Issue is closed.",
    visibleClaims: "Not applicable.",
    linkedPrs: "One merged change referenced in the demo record.",
    blockers: "Not applicable.",
    startSteps: ["Do not start work on this issue.", "Use the repository view to find related open work."],
    setup: ["No setup needed for a closed issue."],
    avoid: [{ kind: "Official repository rule", text: "Closed issues require a new discussion before scope is reopened.", source: { label: "Demo contributing guide", href: "#demo-source-note", kind: "guide" } }],
    sources: [{ label: "Demo closed issue", href: "#demo-source-note", kind: "issue" }]
  },
  {
    id: "event-oss-weekend",
    category: "hackathon",
    organizer: "Demo Open Guild",
    title: "Open Source Weekend",
    summary: "A remote, contributor-focused weekend with maintainer-led project rooms and beginner tracks.",
    status: "closing-soon",
    deadline: "Sep 18, 2026 · 23:59 UTC",
    deadlineAt: "2026-09-18T23:59:00.000Z",
    eligibility: "18+; worldwide except where restricted. Student status not required.",
    format: "Remote · Worldwide",
    team: "Individual registration; teams of 1–4 for demos",
    cost: "Free",
    checkedAt: checked,
    updatedAt: "2026-09-12T01:00:00.000Z",
    experience: "Beginner",
    tags: ["open source", "remote"],
    officialUrl: "https://devpost.com/hackathons",
    sourceNote: "Illustrative demo record. The link opens Devpost’s real hackathon directory, not an application for this fictional event."
  },
  {
    id: "event-civic-data-sprint",
    category: "hackathon",
    organizer: "Demo Civic Stack",
    title: "Civic Data Sprint 2026",
    summary: "A remote build sprint focused on accessible public-data tools, documentation, and reusable community infrastructure.",
    status: "open",
    deadline: "Sep 29, 2026 · 18:00 UTC",
    deadlineAt: "2026-09-29T18:00:00.000Z",
    eligibility: "Worldwide participation; minimum age and regional restrictions unknown.",
    format: "Remote · Worldwide",
    team: "Individuals or teams; maximum team size unknown",
    cost: "Free",
    checkedAt: "2026-09-12T05:20:00.000Z",
    updatedAt: "2026-09-12T05:20:00.000Z",
    experience: "Beginner",
    tags: ["public interest", "beginner friendly", "open ended"],
    officialUrl: "https://devpost.com/hackathons",
    sourceNote: "Illustrative demo record. The link opens Devpost’s real hackathon directory, not an application for this fictional event."
  },
  {
    id: "event-green-build",
    category: "hackathon",
    organizer: "Demo Climate Code",
    title: "Green Build Challenge",
    summary: "An online prototype challenge for tools that help small engineering teams measure and reduce infrastructure waste.",
    status: "upcoming",
    deadline: "Registration date not yet published · timezone unknown",
    eligibility: "Eligibility details not yet published.",
    format: "Online",
    team: "Team requirements unknown",
    cost: "Unknown",
    checkedAt: "2026-09-11T16:00:00.000Z",
    updatedAt: "2026-09-11T16:00:00.000Z",
    experience: "Intermediate",
    tags: ["climate", "cloud", "prototype"],
    officialUrl: "https://unstop.com/hackathons",
    sourceNote: "Illustrative demo record. The link opens Unstop’s real hackathon directory, not an application for this fictional event."
  },
  {
    id: "event-accessibility-lab",
    category: "hackathon",
    organizer: "Demo Inclusive Web Lab",
    title: "Accessible Web Jam",
    summary: "A short hybrid hackathon for improving keyboard, screen-reader, and low-vision experiences in community software.",
    status: "open",
    deadline: "Oct 12, 2026 · 12:00 Asia/Kolkata",
    deadlineAt: "2026-10-12T06:30:00.000Z",
    eligibility: "Students and working professionals; geographic restrictions unknown.",
    format: "Hybrid · Bengaluru and remote",
    team: "Teams of 2–4",
    cost: "Free",
    checkedAt: "2026-09-11T08:30:00.000Z",
    updatedAt: "2026-09-11T08:30:00.000Z",
    experience: "Beginner",
    tags: ["accessibility", "web", "social good"],
    officialUrl: "https://devpost.com/hackathons",
    sourceNote: "Illustrative demo record. The link opens Devpost’s real hackathon directory, not an application for this fictional event."
  },
  {
    id: "program-maintainer-path",
    category: "program",
    organizer: "Demo Commons Foundation",
    title: "Maintainer Path Fellowship",
    summary: "A structured twelve-week program for contributors ready to take on triage, documentation, and release support.",
    status: "open",
    deadline: "Oct 04, 2026 · 17:00 UTC",
    deadlineAt: "2026-10-04T17:00:00.000Z",
    eligibility: "Prior open-source contribution required; geography restrictions unknown.",
    format: "Remote · Location details unknown",
    team: "Individual applications",
    cost: "Unknown",
    checkedAt: "2026-09-11T10:00:00.000Z",
    updatedAt: "2026-09-11T10:00:00.000Z",
    experience: "Intermediate",
    tags: ["fellowship", "maintainers"],
    officialUrl: "https://summerofcode.withgoogle.com/",
    sourceNote: "Illustrative demo record. The link is a real developer-program reference, not an application for this fictional fellowship."
  },
  {
    id: "program-docs-sprint",
    category: "program",
    organizer: "Demo Docs Collective",
    title: "Documentation Residency",
    summary: "A part-time residency for improving setup paths and contributor documentation across small public projects.",
    status: "upcoming",
    deadline: "Applications not yet open · deadline unknown",
    eligibility: "Eligibility details not yet published.",
    format: "Remote status unknown",
    team: "Individual participation",
    cost: "Unknown",
    checkedAt: "2026-09-10T09:00:00.000Z",
    updatedAt: "2026-09-10T09:00:00.000Z",
    experience: "Beginner",
    tags: ["documentation", "program"],
    officialUrl: "https://developers.google.com/season-of-docs",
    sourceNote: "Illustrative demo record. The link is a real documentation-program reference, not an application for this fictional residency."
  }
];
